@@ -0,0 +1,286 @@

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anahí
 */
public class BDD extends javax.swing.JFrame {
int IDCat,IDOrder,Cantidad,method,F;
String territory,category,emailA,emailN;
    /**
     * Creates new form BDD
     */
    public BDD() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaConsultas = new javax.swing.JList<>();
        Ins1 = new javax.swing.JLabel();
        Ins2 = new javax.swing.JLabel();
        TiVar1 = new javax.swing.JLabel();
        TiVar2 = new javax.swing.JLabel();
        Var1 = new javax.swing.JTextField();
        Var2 = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Consultar = new javax.swing.JButton();
        Descripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ListaConsultas.setBackground(new java.awt.Color(204, 255, 153));
        ListaConsultas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", "B", "C", "D", "E", "F", "G" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaConsultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaConsultas);

        Ins1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ins1.setText("1. Escoja una consulta a realizar:");

        Ins2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Ins2.setText("2. Llene los campos solicitados");

        TiVar1.setText("---");

        TiVar2.setText("---");

        Var1.setBackground(new java.awt.Color(204, 204, 255));

        Var2.setBackground(new java.awt.Color(204, 204, 255));

        Titulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Titulo.setText("Fragmentación Horizontal");

        Consultar.setBackground(new java.awt.Color(255, 204, 204));
        Consultar.setText("Consultar");
        Consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarMouseClicked(evt);
            }
        });

        Descripcion.setText("Descripción");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ins1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TiVar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ins2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Var1)
                    .addComponent(TiVar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Var2))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(Titulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(Consultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Titulo)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ins1)
                    .addComponent(Ins2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TiVar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Var1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(TiVar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Var2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(Consultar)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaConsultasMouseClicked
        // TODO add your handling code here:
        Var1.enable(true);
        Var2.enable(true);
        switch (ListaConsultas.getSelectedIndex()){
            case 0:
                TiVar1.setText("ID Categoría");
                TiVar2.setText(""); 
                Descripcion.setText("Determina el total de ventas de los productos para cada territorio de acuerdo a la categoría solicitada");
                Var2.enable(false);
            break;
            case 1:
                TiVar1.setText("Territorio");
                TiVar2.setText("");
                Descripcion.setText("Determinar el producto más solicitado para la región (atributo group de salesterritory)“Noth America”y en que territorio de la región tiene mayor demanda.");
                Var2.enable(false);
            break;
            case 2:
                TiVar1.setText("ID Categoría");
                TiVar2.setText("");
                Descripcion.setText("Actualizar el stock disponibleen un 5%delos productos de la categoría que se provea como argumento de entradaen una localidad que se provea como entrada en la instrucción de actualización");
                Var2.enable(false);
            break;
            case 3:
                TiVar1.setText("");
                TiVar2.setText("");
                Descripcion.setText("Determinar si hay clientes que realizan ordenes en territorios diferentes al que se encuentran. ");
                Var1.enable(false);
                Var2.enable(false);
            break;
            case 4:
                TiVar1.setText("ID Orden");
                TiVar2.setText("Cantidad de productos");   
                Descripcion.setText("Actualizar  la  cantidad  de  productos  de  una  ordenque  seprovea  como argumento en la instrucción de actualización.");
            break;
            case 5:
                TiVar1.setText("ID Orden");
                TiVar2.setText("Método");
                Descripcion.setText("Actualizar el métodode envío de una orden que se reciba como argumento en la instrucción de actualización.");                
            break;
            case 6:
                TiVar1.setText("Email actual");
                TiVar2.setText("Email nuevo");
                Descripcion.setText("Actualizar el correo electrónico de una cliente que se reciba como argumento en la instrucción de actualización.");
            break;
        }
    }//GEN-LAST:event_ListaConsultasMouseClicked

    private void ConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarMouseClicked
        // TODO add your handling code here:
        switch (F){
            case 0:
                IDCat=Integer.parseInt(Var1.getText());
            break;
            case 1:
                territory=Var1.getText();
            break;
            case 2:
                category=Var1.getText();
            break;
            case 3:
            break;
            case 4:
                IDOrder=Integer.parseInt(Var1.getText());
                Cantidad=Integer.parseInt(Var2.getText());
            break;
            case 5:
                IDOrder=Integer.parseInt(Var1.getText());
                method=Integer.parseInt(Var2.getText());
            break;
            case 6:
                emailA=Var1.getText();
                emailN=Var2.getText();
            break;
        }
    }//GEN-LAST:event_ConsultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Ins1;
    private javax.swing.JLabel Ins2;
    private javax.swing.JList<String> ListaConsultas;
    private javax.swing.JLabel TiVar1;
    private javax.swing.JLabel TiVar2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField Var1;
    private javax.swing.JTextField Var2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
